name: CI/CD MLflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  packages: write

env:
  CSV_URL: "MLProject/titanic_clean.csv"
  TARGET_VAR: "Survived"

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
          - name: Run actions/checkout@v3
            uses: actions/checkout@v3

          - name: Set up Python 3.12.7
            uses: actions/setup-python@v4
            with:
              python-version: "3.12.7"

          - name: Check Env
            run: |
              echo $CSV_URL

          - name: Install Dependencies
            run: |
              python -m pip install --upgrade pip
              pip install mlflow dagshub seaborn matplotlib scikit-learn pandas numpy

          - name: Run MLFlow Project
            run: |
              mlflow run MLProject --env-manager=local

          - name: Get latest MLFlow run_id
            run: |
              RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
              echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
              echo "Latest run_id: $RUN_ID"

          - name: Upload ML Model Artifacts to 
            uses: actions/upload-artifact@v4
            with:
              name: ml-model-artifact
              path: mlruns/0/${{ env.RUN_ID }}/artifacts/model

          - name: Build Docker Model
            run: |
              mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "titanic-prediction-model"

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}

          - name: Tag Docker Image
            run: |
              docker tag titanic-prediction-model ${{ secrets.DOCKERHUB_USERNAME }}/titanic-prediction-model:latest

          - name: Push Docker Image
            run: |
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/titanic-prediction-model:latest

          - name: Login to GitHub Container Registry
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Build and Tag Docker Image for GitHub Packages
            run: |
              mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "titanic-prediction-model"
              docker tag titanic-prediction-model ghcr.io/${{ github.repository_owner }}/titanic-prediction-model:latest

          - name: Push to GitHub Packages
            run: |
              docker push ghcr.io/${{ github.repository_owner }}/titanic-prediction-model:latest
